### ISSUE TITLE
Data not available anymore at Kaggle

### ISSUE THREAD

**Issue by raviprakashmishra** [bernhard2202/twitter-sentiment-analysis#32]
Hi,
I wanted to understand your code through training in my local machine. I see that data required is not available at Kaggle anymore. Is that data is similar to this - http://help.sentiment140.com/for-students/

**Comment by AndreiBarsan** [comment]
Hi, I believe that that particular dataset is not open to the public, since this was a university project. However, the system should, in theory, work with any sentiment analysis dataset, as long as it's preprocessed to remove non-ASCII characters and pre-tokenized.
