### ISSUE TITLE
How to run your code locally? 

### ISSUE THREAD

**Issue by nargesam** [bernhard2202/twitter-sentiment-analysis#33]
Hi, I would like to use your model to run on my tweet dataset. How would I run it  locally, instead of running fabfile.py for AWS?

**Comment by AndreiBarsan** [comment]
Hi, nargesam, please look at the function `_run_tf` in `fabfile.py`. For more details, see `train_model.py`. Note that this is a pretty old repo, so you can very likely get much better results using some more modern language modeling and classification techniques. Hope this helps!
